style:
  MaxLineLength:
    maxLineLength: 160

  ReturnCount:
    max: 5

  WildcardImport:
    active: false

complexity:
  LongParameterList:
    constructorThreshold: 15

  TooManyFunctions:
    thresholdInFiles: 16
    ignorePrivate: true

  ComplexCondition:
    threshold: 10
